name: send workflow result email
description: send workflow result email

inputs:
  mail_reciever:
    description: 'Email reciever'
    required: true
  linter_result:
    description: 'Linter job result'
    required: true
  cypress_result:
    description: 'Cypress job result'
    required: true
  badge_result:
    description: 'Badge job result'
    required: true
  deploy_result:
    description: 'Deploy job result'
    required: true

runs:
  using: 'node20'
  main: 'dist/main.js'