name: nodejs-blog-practica
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: npm

      - name: install deps
        run: npm ci
      
      - name: run linter
        run: npm run lint

  cypress:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: checkout code
        uses: actions/checkout@v5
  
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: npm

      - name: install deps
        run: npm ci

      - name: run cypress tests
        uses: cypress-io/github-action@v6
        id: cypress
        continue-on-error: true
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

      - name: save cypress output to result.txt
        run: echo "${{ steps.cypress.outcome }}" > result.txt

      - name: upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.txt

      - name: output
        run: echo "outcome=${{ steps.cypress.outcome }}" >> $GITHUB_OUTPUT

  add_badge:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: update badge in README
        uses: ./.github/actions/cypress-outcome-readme
        with:
          cypress_outcome: ${{ needs.cypress.outputs.outcome }}

      - name: commit and push badge update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com" 
          if ! git diff --quiet; then
            git add README.md
            git commit -m "Update Cypress test badge"
            git push
          fi
  deploy_vercel:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

  notification:
