name: nodejs-blog-practica
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup node install deps
        uses: actions/setup-node@v6
        with:
          node-version: '20'
        run: npm i
      
      - name: run linter
        run: npm run lint
        