name: nodejs-blog-practica
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: install deps
        run: npm ci
      
      - name: run linter
        run: npm run lint
        